* Chapter 2.3 Exercise Solutions

** Exercise 1
- Analyze the logical forms of the following statements.

*** 1a
F âŠ† ğ’«(A)
F âŠ† {x \vert x âŠ† A }
âˆ€x(x âˆˆ F â†’ {x \vert x âŠ† A })
âˆ€x(x âˆˆ F â†’ âˆ€y(y âˆˆ x â†’ y âˆˆ A))

*** 1b
A âŠ† {2n + 1 | n âˆˆ â„•}
âˆ€x(x âˆˆ A â†’ x âˆˆ {2n + 1 | n âˆˆ â„•})
âˆ€x(x âˆˆ A â†’ âˆƒn âˆˆ â„•(x = 2n + 1))

*** 1c
{n^2 + n + 1 | n âˆˆ â„•} âŠ† {2n + 1 | n âˆˆ â„•}

âˆ€x(x âˆˆ {n^2 + n + 1 | n âˆˆ â„•} â†’ x âˆˆ {2n + 1 | n âˆˆ â„•})
âˆ€x(âˆƒn âˆˆ â„•(x = n^2 + n + 1) â†’ âˆƒm âˆˆ â„•(x = 2m + 1))
âˆ€n âˆˆ â„•âˆƒm âˆˆ â„•(n^2 + n + 1 = 2m + 1)

*** 1d
ğ’«(âˆª_{iâˆˆI}A_i) âŠ„ âˆª_{iâˆˆI}ğ’«(A_i)
âˆƒx(x âˆˆ ğ’«(âˆª_{iâˆˆI}A_i) âˆ§ x âˆ‰ âˆª_{iâˆˆI}ğ’«(A_i))

x âˆˆ ğ’«(âˆª_{iâˆˆI}A_i):
âˆ€y(y âˆˆ x â†’ y âˆˆ âˆª_{iâˆˆI}A_i)
âˆ€y(y âˆˆ x â†’ y âˆˆ {t \vert âˆƒi âˆˆ I(t âˆˆ A_i)})
âˆ€y(y âˆˆ x â†’ âˆƒi âˆˆ I(y âˆˆ A_i))

x âˆ‰ âˆª_{iâˆˆI}ğ’«(A_i):
x âˆ‰ {t | âˆƒi âˆˆ I(t âˆˆ ğ’«(A_i))}
âˆƒi âˆˆ I(x âˆ‰ ğ’«(A_i))
âˆƒi âˆˆ I(x âˆ‰ {z | z âŠ† A_i })
âˆƒi âˆˆ I(x âŠ„ A_i)
âˆƒi âˆˆ Iâˆƒy(y âˆˆ x âˆ§ y âˆ‰ A_i)

âˆƒx(x âˆˆ ğ’«(âˆª_{iâˆˆI}A_i) âˆ§ x âˆ‰ âˆª_{iâˆˆI}ğ’«(A_i))
âˆƒx(âˆ€y(y âˆˆ x â†’ âˆƒi âˆˆ I(y âˆˆ A_i)) âˆ§ âˆƒi âˆˆ Iâˆƒy(y âˆˆ x âˆ§ y âˆ‰ A_i))

** Exercise 2
*** 2a
x âˆˆ âˆªF \ âˆªG
x âˆˆ âˆªF âˆ§ x âˆ‰ âˆªG
âˆƒA âˆˆ F(x âˆˆ A) âˆ§ Â¬âˆƒA âˆˆ G(x âˆˆ A)
âˆƒA âˆˆ F(x âˆˆ A) âˆ§ âˆ€A âˆˆ G(x âˆ‰ A)

*** 2b
{x âˆˆ B | x âˆ‰ C} âˆˆ ğ’«(A)
{x âˆˆ B | x âˆ‰ C} âˆˆ {x \vert x âŠ† A }
{x âˆˆ B | x âˆ‰ C} âŠ† A
âˆ€y(y âˆˆ {x âˆˆ B | x âˆ‰ C} â†’ y âˆˆ A)
âˆ€y({y âˆˆ B | y âˆ‰ C} â†’ y âˆˆ A)
âˆ€y(y âˆˆ B âˆ§ y âˆ‰ C â†’ y âˆˆ A)

*** 2c
x âˆˆ âˆ©_{iâˆˆI}(A_i âˆª B_i)
x âˆˆ {x \vert âˆ€i âˆˆ I(x âˆˆ (A_i âˆª B_i))}
âˆ€i âˆˆ I(x âˆˆ (A_i âˆª B_i))
âˆ€i âˆˆ I(x âˆˆ A_i âˆ¨ x âˆˆ B_i)

*** 2d
x âˆˆ (âˆ©_{iâˆˆI}A_i) âˆª (âˆ©_{iâˆˆI}B_i)
(âˆ€i âˆˆ I(x âˆˆ A_i)) âˆ¨ (âˆ€i âˆˆ I(x âˆˆ B_i))

** Exercise 3
ğ’«({âˆ…}) = {âˆ…, {âˆ…}}
âˆ… is a subset of the set (it is of all sets).
{âˆ…} is the subset containing the one element of the set.

** Exercise 4
âˆ©F = {red, blue}
âˆªF = {red, green, blue, orange, purple}

** Exercise 5
âˆ©F = âˆ…
âˆªF = {3, 7, 12, 5, 16, 23}

** Exercise 6
*** 6a
A_2 = {2,3,1,4}
A_3 = {3,4,2,6}
A_4 = {4,5,3,8}
A_5 = {5,6,4,10}

*** 6b
âˆ©_{iâˆˆI}A_i = {4}
âˆª_{iâˆˆI}A_i = {1,2,3,4,5,6,8,10}

** Exercise 7
Ugh, really?

** Exercise 8
*** 8a
A_2 = {2,4}
A_3 = {3,6}

B_2 = {2,3}
B_3 = {3,4}

*** 8b
âˆ©_{iâˆˆI}(A_i âˆª B_i) = âˆ©{2,3,4}{3,4,6}
            = {3,4}

(âˆ©_{iâˆˆI}A_i) âˆª (âˆ©_{iâˆˆI}B_i) = {} âˆª {3}
                 = {3}

They are not the same.

*** 8c
From our answer in 8b, we can conclude that x âˆˆ âˆ©_{iâˆˆI}(A_i âˆª B_i) and x âˆˆ (âˆ©_{iâˆˆI}A_i) âˆª
(âˆ©_{iâˆˆI}B_i) are *not* equivalent statements.

** Exercise 9
I = {2, 3}
A_i = {i,2i}
B_i = {i,i+1}

A_2 = {2,4}
A_3 = {3,6}
B_2 = {2,3}
B_3 = {3,4}

âˆª_{iâˆˆI}(A_i âˆ© B_i)      = âˆª{2}{3}             = {2,3}
(âˆª_{iâˆˆI}A_i) âˆ© (âˆª_{iâˆˆI}B_i) = {2,3,4,6} âˆ© {2,3,4} = {2,3,4}

** Exercise 10

x âˆˆ ğ’«(A âˆ© B)
x âˆˆ {x \vert x âŠ† A âˆ© B }
x âŠ† A âˆ© B
âˆ€y(y âˆˆ x â†’ y âˆˆ A âˆ© B)
âˆ€y(y âˆˆ x â†’ y âˆˆ A âˆ§ y âˆˆ B)
âˆ€y(y âˆ‰ x âˆ¨ (y âˆˆ A âˆ§ y âˆˆ B)) [conditional law]
âˆ€y((y âˆ‰ x âˆ¨ y âˆˆ A) âˆ§ (y âˆ‰ x âˆ¨ y âˆˆ B)) [distributive law]
âˆ€y((y âˆˆ x â†’ y âˆˆ A) âˆ§ (y âˆˆ x â†’ y âˆˆ B)) [conditional law]

x âˆˆ ğ’«(A) âˆ© ğ’«(B)
x âˆˆ {x \vert x âŠ† A } âˆ© {x \vert x âŠ† B }
x âŠ† A âˆ§ x âŠ† B
âˆ€y(y âˆˆ x â†’ y âˆˆ A) âˆ§ âˆ€y(y âˆˆ x â†’ y âˆˆ B)
âˆ€y((y âˆˆ x â†’ y âˆˆ A) âˆ§ (y âˆˆ x â†’ y âˆˆ B)), which is equivalent to above.

** Exercise 11

A = {1,2}
B = {2,3}

ğ’«(A âˆª B)    = ğ’«({1,2,3})
            = {âˆ…, {1}, {2}, {3}, {1,2}, {1,3}, {2,3}}

ğ’«(A) âˆª ğ’«(B) = {âˆ…, {1}, {2}, {1,2}} âˆª {âˆ…, {2}, {3}, {2,3}}
            = {âˆ…, {1}, {2}, {3}, {1,2}, {2,3}}

** Exercise 12
*** 12a
âˆª_{iâˆˆI}(A_i âˆª B_i):
x âˆˆ âˆª_{iâˆˆI}(A_i âˆª B_i)
x âˆˆ {x \vert âˆƒi âˆˆ I(x âˆˆ (A_i âˆª B_i))}
âˆƒi âˆˆ I(x âˆˆ (A_i âˆª B_i))
âˆƒi âˆˆ I(x âˆˆ A_i âˆ¨ x âˆˆ B_i)

(âˆª_{iâˆˆI}A_i) âˆª (âˆª_{iâˆˆI}B_i):
x âˆˆ (âˆª_{iâˆˆI}A_i) âˆª (âˆª_{iâˆˆI}B_i)
x âˆˆ (âˆª_{iâˆˆI}A_i) âˆ¨ x âˆˆ (âˆª_{iâˆˆI}B_i)
x âˆˆ {x \vert âˆƒi âˆˆ I(x âˆˆ A_i)} âˆ¨ x âˆˆ {x \vert âˆƒi âˆˆ I(x âˆˆ B_i)}
âˆƒi âˆˆ I(x âˆˆ A_i) âˆ¨ âˆƒi âˆˆ I(x âˆˆ B_i)
âˆƒi âˆˆ I(x âˆˆ A_i âˆ¨ x âˆˆ B_i)

Therefore âˆª_{iâˆˆI}(A_i âˆª B_i) = (âˆª_{iâˆˆI}A_i) âˆª (âˆª_{iâˆˆI}B_i).

*** 12b
(âˆ©F)âˆ©(âˆ©G) = âˆ©(F âˆª G)

(âˆ©F)âˆ©(âˆ©G):
x âˆˆ (âˆ©F)âˆ©(âˆ©G)
(x âˆˆ âˆ©F) âˆ§ (x âˆˆ âˆ©G)
x âˆˆ {x \vert âˆ€A âˆˆ F(x âˆˆ A)} âˆ§ x âˆˆ {x \vert âˆ€A âˆˆ G(x âˆˆ A)}
âˆ€A âˆˆ F(x âˆˆ A) âˆ§ âˆ€A âˆˆ G(x âˆˆ A)

âˆ©(F âˆª G):
x âˆˆ {x \vert âˆ€A âˆˆ (F âˆª G)(x âˆˆ A)}
âˆ€A âˆˆ (F âˆª G)(x âˆˆ A)
âˆ€A(A âˆˆ (F âˆª G) â†’ x âˆˆ A)
âˆ€A((A âˆˆ F âˆ¨ A âˆˆ G) â†’ x âˆˆ A)
âˆ€A(Â¬(A âˆˆ F âˆ¨ A âˆˆ G) âˆ¨ x âˆˆ A)           [conditional law]
âˆ€A((A âˆ‰ F âˆ§ A âˆ‰ G) âˆ¨ x âˆˆ A)            [DeMorgan's law]
âˆ€A((A âˆ‰ F âˆ¨ x âˆˆ A) âˆ§ (A âˆ‰ G âˆ¨ x âˆˆ A))  [distributive law]
âˆ€A((A âˆˆ F â†’ x âˆˆ A) âˆ§ (A âˆˆ G â†’ x âˆˆ A))  [conditional law]
âˆ€A(A âˆˆ F â†’ x âˆˆ A) âˆ§ âˆ€A(A âˆˆ G â†’ x âˆˆ A)  [âˆ€ distributes over âˆ§]
âˆ€A âˆˆ F(x âˆˆ A) âˆ§ âˆ€A âˆˆ G(x âˆˆ A)

Therefore (âˆ©F)âˆ©(âˆ©G) = âˆ©(F âˆª G).

*** 12c
âˆ©_{iâˆˆI}(A_i \ B_i) = âˆ©_{iâˆˆI}A_i \ âˆª_{iâˆˆI}B_i

âˆ©_{iâˆˆI}(A_i \ B_i):
x âˆˆ {x \vert âˆ€i âˆˆ I(x âˆˆ (A_i \ B_i))}
âˆ€i âˆˆ I(x âˆˆ (A_i \ B_i))
âˆ€i âˆˆ I(x âˆˆ A_i âˆ§ x âˆ‰ B_i) [defn. of set difference]

âˆ©_{iâˆˆI}A_i \ âˆª_{iâˆˆI}B_i:
x âˆˆ âˆ©_{iâˆˆI}A_i \ âˆª_{iâˆˆI}B_i
x âˆˆ âˆ©_{iâˆˆI}A_i âˆ§ x âˆ‰ âˆª_{iâˆˆI}B_i [defn. of set difference]
x âˆˆ {x \vert âˆ€i âˆˆ I(x âˆˆ A_i)} âˆ§ x âˆ‰ {x \vert âˆƒi âˆˆ I(x âˆˆ B_i)}
âˆ€i âˆˆ I(x âˆˆ A_i) âˆ§ Â¬(âˆƒi âˆˆ I(x âˆˆ B_i))
âˆ€i âˆˆ I(x âˆˆ A_i) âˆ§ âˆ€i âˆˆ I(x âˆ‰ B_i) [quantifier negation law]
âˆ€i âˆˆ I(x âˆˆ A_i âˆ§ x âˆ‰ B_i)

** Exercise 13
I = {1,2}
J = {3,4}
A_{i,j} = {i,j,i+j}

*** 13a
For each j âˆˆ J, let B_j = âˆª_{iâˆˆI}A_i,j = A_1,j âˆª A_2,j. Find B_3 and B_4.
B_3 = A_1,3 âˆª A_2,3
   = {1,3,4} âˆª {2,3,5}
   = {1,2,3,4,5}

B_4 = A_1,4 âˆª A_2,4
   = {1,4,5} âˆª {2,4,6}
   = {1,2,4,5,6}

*** 13b
âˆ©_{jâˆˆJ}B_j = âˆ©_{jâˆˆJ}(âˆª_{iâˆˆI}A_{i,j})
âˆ©_{jâˆˆJ}(âˆª_{iâˆˆI}A_{i,j})
âˆ©_{jâˆˆJ}(A_{1,j} âˆª A_{2,j})
((A_{1,3} âˆª A_{2,3}) âˆ© (A_{1,4} âˆª A_{2,4}))
(({1,3,4} âˆª {2,3,5}) âˆ© ({1,4,5} âˆª {2,4,6}))
{1,2,3,4,5} âˆ© {1,2,4,5,6}
{1,2,4,5}

*** 13c
âˆª_{iâˆˆI}_{}_{}(âˆ©_{jâˆˆJ}_{}A_{i,j})
âˆª_{iâˆˆI}_{}_{}(A_{i,3} âˆ© A_{i,4})
(A_{1,3} âˆ© A_{1,4}) âˆª (A_{2,3} âˆ© A_{2,4})
({1,3,4} âˆ© {1,4,5}) âˆª ({2,3,5} âˆ© {2,4,6})
{1,4} âˆª {2}
{1,2,4}

âˆª_{iâˆˆI}_{}_{}(âˆ©_{jâˆˆJ}_{}A_{i,j}) and âˆ©_{jâˆˆJ}(âˆª_{iâˆˆI}A_{i,j}) are not equal.

*** 13d
âˆª_{iâˆˆI}_{}_{}(âˆ©_{jâˆˆJ}_{}A_{i,j}):
x âˆˆ âˆª_{iâˆˆI}_{}_{}(âˆ©_{jâˆˆJ}_{}A_{i,j})
x âˆˆ {x \vert âˆƒi âˆˆ I(x âˆˆ (âˆ©_{jâˆˆJ}_{}A_{i,j}))}
âˆƒi âˆˆ I(x âˆˆ (âˆ©_{jâˆˆJ}_{}A_{i,j}))
âˆƒi âˆˆ I(x âˆˆ ({x \vert âˆ€j âˆˆ J(x âˆˆ A_{i,j})}))
âˆƒi âˆˆ I(âˆ€j âˆˆ J(x âˆˆ A_{i,j}))


âˆ©_{jâˆˆJ}(âˆª_{iâˆˆI}A_{i,j}):
x âˆˆ âˆ©_{jâˆˆJ}(âˆª_{iâˆˆI}A_{i,j})
x âˆˆ {x \vert âˆ€j âˆˆ J(x âˆˆ (âˆª_{iâˆˆI}A_{i,j}))}
âˆ€j âˆˆ J(x âˆˆ (âˆª_{iâˆˆI}A_{i,j}))
âˆ€j âˆˆ J(âˆƒi âˆˆ I(x âˆˆ A_{i,j}))

They are not equivalent.

** Exercise 14
*** 14a
x âˆˆ âˆªF
x âˆˆ {x \vert âˆƒA âˆˆ F(x âˆˆ A)}
âˆƒA âˆˆ F(x âˆˆ A)
âˆƒA(A âˆˆ F âˆ§ x âˆˆ A)
âˆƒA(A âˆˆ âˆ… âˆ§ x âˆˆ A) [F = âˆ…]

A âˆˆ âˆ… is always false and so (A âˆˆ âˆ… âˆ§ x âˆˆ A) will always be false.

*** 14b
x âˆˆ âˆ©F
x âˆˆ {x \vert âˆ€A âˆˆ F(x âˆˆ A)}
âˆ€A âˆˆ F(x âˆˆ A)
âˆ€A(A âˆˆ F â†’ x âˆˆ A)
âˆ€A(A âˆ‰ F âˆ¨ x âˆˆ A) [conditional equivalence]
âˆ€A(A âˆ‰ âˆ… âˆ¨ x âˆˆ A) [F = âˆ…]

A âˆ‰ âˆ… is always true so (A âˆ‰ âˆ… âˆ¨ x âˆˆ A) will also always be true.

** Exercise 15
*** 15a
Let R be all sets that are not elements of themselves.
R = {A âˆˆ U | A âˆ‰ A}
âˆ€A âˆˆ U(A âˆˆ R â†” A âˆ‰ A)
R âˆˆ âˆ€A âˆˆ U(A âˆˆ R â†” A âˆ‰ A)
(R âˆˆ R â†” R âˆ‰ R)
(T â†” F)
(T â†’ F) âˆ§ (F â†’ T) [biconditional equivalence]
(F âˆ¨ F) âˆ§ (T âˆ¨ T) [conditional equivalence]
F âˆ§ T
F [contradiction]

*** 15b
A universal set of sets does not exist, the universal set can't contain itself.
